### ISSUE TITLE
Top returns an empty array

### ISSUE THREAD

**Issue by jcloquell** [davidsantosmerino/filmaffinity-api#1]
Just found this API (nice job!) but it doesn't matter what parameters (or no parameter at all) you set in the `top` query, it always returns an empty array. Maybe they changed something in the website and the script needs to be adapted? do you have any plan to keep working on this API?

**Comment by oricodes89** [comment]
Hi @jcloquell, 

@dsantosmerino and I will do our best to fix this asap. Thank you!

**Comment by dsantosmerino** [comment]
@jcloquell we've updated some anchors and now it's working properly. Let us know if you need something more!
