### ISSUE TITLE
API doesn´t work

### ISSUE THREAD

**Issue by rodrirepresa** [davidsantosmerino/filmaffinity-api#4]
Sorry the Api doesn´t work.
Thanks!!

**Comment by cdfaux** [comment]
rodriRR, the api work perfectly. Tested Yesterday.
Regard

**Comment by dsantosmerino** [comment]
Hey @RodriRR, as @cdfaux says it looks good to me. I'll close the issue, feel free to reopen if you find an edge case that we didn't realize.
